#:schema node_modules/wrangler/config-schema.json
name = "gecko-sales-bot"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true
