#:schema node_modules/wrangler/config-schema.json
name = "gecko-sales-bot"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
